---
- name: classify hosts by os distribution
  hosts: all
  tasks:
    - name: classify hosts depending on their os distribution
      group_by:
        key: os_{{ ansible_facts['os_family'] }}
      changed_when: false
  tags: minimal

- name: configure dotfiles and developer tools
  hosts: all
  connection: local
  roles:
    - {role: dotfiles, tags: [minimal]}
    - developer

- name: configure macos applications and defaults
  hosts: os_Darwin
  connection: local
  roles:
   - {role: osx-apps, tags: [osx]}
   - {role: osx-defaults, tags: [osx]}

- name: configure arch linux applications
  hosts: os_Archlinux
  connection: local
  roles:
    - {role: linux-apps, tags: []}
