---
- name: prepare machine for converging
  hosts: all
  tasks:
    - name: copy bootstrap script for execution
      command: docker cp {{playbook_dir}}/bootstrap.sh {{ ansible_fqdn }}:/tmp
      delegate_to: 127.0.0.1

    - name: bootstrap the machine
      command: bash /tmp/bootstrap.sh
      environment:
        NO_PROVISION: 1
  tags: minimal
