# custom path for rbenv see - https://github.com/rbenv/rbenv
export PATH="$HOME/bin/:$HOME/.rbenv/shims:$PATH"

# fasd aliases see - https://github.com/clvv/fasd

alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection

# git aliases

alias gst='git status'
alias gj='git jira'
alias gd='git diff'
alias gdc='git diff --cached'

# use sublime as the default editor

export EDITOR='subl -w'
export VISUAL='subl -w'

# set our prompt

autoload -Uz promptinit
promptinit
prompt pure

# heroku aliases

alias h="heroku"
alias hl="heroku logs -t"
alias hc="heroku run console"
alias hr="heroku run"
alias hp="heroku ps"
alias hnr="heroku addons:open newrelic"

# ls aliases

eval $(gdircolors ~/.dircolors/dircolors.256dark)

alias ls='\gls --color=auto' # use coretuils gnu ls which supports 256 colors
alias ll='ls -al'

# lesspipe

export LESSOPEN="|/usr/local/bin/lesspipe.sh %s" LESS_ADVANCED_PREPROCESSOR=1

# get the weather

alias weather="curl wttr.in/Melbourne"

# iTerm 2 Integration see https://www.iterm2.com/documentation-shell-integration.html
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
