---
- name: create temporary install directory for oh-my-zsh
  ansible.builtin.tempfile:
    state: directory
    prefix: oh-my-zsh
  register: dotfiles_tempdir

- name: get oh-my-zsh install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: "{{ dotfiles_tempdir.path }}/install.sh"
    mode: "0755"

- name: execute oh my zsh setup script
  ansible.builtin.command: "sh {{ dotfiles_tempdir.path }}/install.sh"

- name: check for zsh binary path
  ansible.builtin.shell: which zsh
  register: dotfiles_zsh_path
  changed_when: false

- name: ensure zsh is an allowable shell
  ansible.builtin.lineinfile:
    path: /etc/shells
    regexp: "{{ dotfiles_zsh_path.stdout | regex_escape }}"
    insertafter: EOF
    state: present
    line: "{{ dotfiles_zsh_path.stdout }}"
  become: true

- name: setting zsh as the default shell
  ansible.builtin.shell: "chsh --shell {{ dotfiles_zsh_path.stdout }} {{ ansible_user  }}"
  become: true
