# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="yuhonas"

# ------------------------------
# Aliases
# ------------------------------
alias h="history"
alias hgrep="history | grep"
alias gbs="git for-each-ref --sort=-committerdate refs/heads/ --format='%(committerdate:short) %(authorname) %(refname:short)'"
# alias git to hub (https://github.com/github/hub)
#alias git="hub"
alias cp="cp -v"
alias bb='babushka'

stb()
{
  BUNDLED_GEM_PATH=`bundle show $1`
  if [ $? -eq 0 ]
  then
    '/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl' $BUNDLED_GEM_PATH
    return 0
  else
    echo "Error: Could not find supplied gem '$1'"
    return 1
  fi
}

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
#DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails3 git textmate ruby lighthouse)
plugins=(sublime git brew gem osx rails zsh-syntax-highlighting autojump bundler)

source $ZSH/oh-my-zsh.sh

# Use alt-(left|right) arrow keys for backword & forward key navigation
bindkey '^[^[[D' backward-word
bindkey '^[^[[C' forward-word

export NODE_PATH=/usr/local/lib/node_modules
export PATH=/Users/locomote/.rvm/gems/ruby-1.9.3-p194/bin:/Users/locomote/.rvm/gems/ruby-1.9.3-p194@global/bin:/Users/locomote/.rvm/rubies/ruby-1.9.3-p194/bin:/Users/locomote/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/locomote/bin:$PATH
export DOCKER_HOST=tcp://localhost:4243
export LESS=-FXR

if [ -f `brew --prefix`/etc/autojump ]; then
  . `brew --prefix`/etc/autojump
fi

