---
- name: install packages needed to take a screenshat
  package:
    name:
      - imagemagick
      - konsole
      - neofetch
      - xvfb
    state: present
  become: true

- name: check for existing xvfb server
  command: xdpyinfo -display :{{ display_server }}
  register: xserver_running
  ignore_errors: true

- name: start xvfb server
  shell: "Xvfb :{{ display_server }} -screen 0 640x480x24 &"
  when: xserver_running is failed

- name: start konsole
  shell: konsole --noclose --fullscreen -e neofetch &
  environment:
    DISPLAY: :{{ display_server }}

- name: get a temporary filename for the screenshot
  tempfile:
    state: file
    suffix: ".png"
  register: screenshot_file

- name: take a screenshot
  shell: import -window root {{ screenshot_file.path }}
  environment:
    DISPLAY: :{{ display_server }}

- name: copy screenshot to local machine
  fetch:
    src: "{{ screenshot_file.path }}"
    dest: screenshot.png
    flat: yes
    validate_checksum: no

- name: terminate xvfb server
  command: pkill Xvfb
