---
- name: install packages needed to take a screenshot
  package:
    name:
      - konsole
      - imagemagick
      - neofetch
      - procps # for process management
      - xorg-server-xvfb
      - xorg-font-util
      - xorg-xdpyinfo
      - ttf-hack # the terminal font I use
    state: present
    update_cache: yes
  become: true

- name: copy over a custom neofetch config for the screenshot
  copy:
    src: config.conf
    dest: "{{ ansible_env.HOME }}/.config/neofetch/"

- name: check for existing xvfb server
  command: xdpyinfo -display :{{ display_server }}
  register: xserver_running
  failed_when: xserver_running.rc > 1 # 1 will be returned when a display server is not found
  changed_when: false

- name: start xvfb server
  shell: "Xvfb :{{ display_server }} -screen 0 640x480x24 &"
  when: '"unable to open display" in xserver_running.stderr'
  changed_when: false

- name: start terminal
  shell: konsole --hide-menubar --hide-tabbar --noclose --fullscreen -e neofetch &
  environment:
    DISPLAY: :{{ display_server }}
  changed_when: false

- name: get a temporary filename for the screenshot
  tempfile:
    state: file
    suffix: ".png"
  register: screenshot_file
  changed_when: false

- name: take a screenshot
  shell: import -trim -window root {{ screenshot_file.path }}
  environment:
    DISPLAY: :{{ display_server }}

- name: crop the screenshot
  shell: mogrify -crop 620x250+0+0 {{ screenshot_file.path }}

- name: copy screenshot to local machine
  fetch:
    src: "{{ screenshot_file.path }}"
    dest: screenshot.png
    flat: yes
    validate_checksum: no
  changed_when: false

- name: terminate xvfb server
  command: pkill Xvfb
  changed_when: false
