---
- name: add alacritty repo
  apt_repository:
    repo: ppa:mmstick76/alacritty
    state: present
  become: true

- name: install packages needed to take a screenshot
  package:
    name:
      # - alacritty
      - konsole
      - imagemagick
      - neofetch
      - xvfb
      # - x11-utils
    state: present
  become: true

- name: check for existing xvfb server
  command: xdpyinfo -display :{{ display_server }}
  register: xserver_running
  ignore_errors: true
  changed_when: false

- name: start xvfb server
  shell: "Xvfb :{{ display_server }} -screen 0 800x600x24 &"
  when: xserver_running is failed
  changed_when: false
  # shell: alacritty --hold --position 0 0 -e neofetch &

- name: start terminal
  shell: konsole --hide-menubar --hide-tabbar --noclose --fullscreen -e neofetch &
  environment:
    DISPLAY: :{{ display_server }}
  changed_when: false

- name: get a temporary filename for the screenshot
  tempfile:
    state: file
    suffix: ".png"
  register: screenshot_file
  changed_when: false

- name: take a screenshot
  shell: import -window root -trim {{ screenshot_file.path }}
  environment:
    DISPLAY: :{{ display_server }}
  changed_when: false

- name: copy screenshot to local machine
  fetch:
    src: "{{ screenshot_file.path }}"
    dest: screenshot.png
    flat: yes
    validate_checksum: no
  changed_when: false

- name: terminate xvfb server
  command: pkill Xvfb
  changed_when: false
