---
driver:
  name: "docker"
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: "instance"
    image: "ubuntu:latest"
    env:
      PATH: "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
      ANSIBLE_USER: "linuxbrew"
      SUDO_GROUP: "admin"
      DEPLOY_GROUP: "deployer"
      SHELL: "/bin/bash"
provisioner:
  name: "ansible"
  env:
    PATH: "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
  inventory:
    host_vars:
      instance:
        ansible_user: "linuxbrew"
  options:
    tags: "minimal"
  playbooks:
    prepare: "../../prepare.yml"
    converge: "../../playbook.yml"
verifier:
  name: "testinfra"
