---
driver:
  name: "docker"
lint: |
  set -e
  # yamllint .
  ansible-lint -x formatting playbook.yml roles/
  flake8
platforms:
  - name: "molecule_instance"
    image: "archlinux/archlinux:latest"
    env:
      PATH: "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
      ANSIBLE_USER: "linuxbrew"
      SUDO_GROUP: "wheel"
      DEPLOY_GROUP: "deployer"
provisioner:
  name: "ansible"
  env:
    PATH: "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
  inventory:
    host_vars:
      molecule_instance:
        ansible_user: "linuxbrew"
  options:
    tags: "minimal"
  playbooks:
    prepare: "../../prepare.yml"
    converge: "../../playbook.yml"
verifier:
  name: "testinfra"
  options:
    s: false # set to true for test debugging see https://docs.pytest.org/en/latest/capture.html
