---
- name: Verify the basics
  hosts: all
  gather_facts: false
  tags: minimal

  tasks:
    - name: get default shell of ansible user
      shell: "cat /etc/passwd | grep {{ ansible_ssh_user }}"
      register: ansible_ssh_user_shell

    - name: get installed zsh module count
      shell: "zsh -ci 'znap status | wc -l'"
      register: zsh_installed_module_count

    - name: run brew from zsh
      shell: "zsh -c 'brew --version'"
      ignore_errors: yes
      register: brew_from_zsh

    - assert:
        that:
          - "'zsh' in ansible_ssh_user_shell.stdout"
          - "'11' in zsh_installed_module_count.stdout_lines"
          - "brew_from_zsh.failed == false"
