---
- name: Verify the basics
  hosts: all
  gather_facts: false
  tags: minimal

  tasks:
    - name: get default shell of ansible user
      ansible.builtin.shell: |
        set -o pipefail
        cat /etc/passwd | grep {{ ansible_user }}
      args:
        executable: /bin/bash
      register: ansible_user_shell

    - name: gather essential CLI tools are on PATH in zsh
      ansible.builtin.shell: "command -v {{ item }}"
      loop:
        - eza
        - git
        - nvim
        - starship
        - zoxide
      register: verify_tools
      changed_when: false

    # NOTE: This is just a non-exhaustive sanity check
    - name: sanity check essential CLI tools returned did not fail
      ansible.builtin.assert:
        that:
          - item.failed == false
        fail_msg: "{{ item.item }} not found in zsh PATH"
      loop: "{{ verify_tools.results }}"
      loop_control:
        label: "{{ item.item }}"


    - name: get installed zsh module count
      ansible.builtin.shell: |
        set -o pipefail
        zsh -ci 'znap status | wc -l'
      args:
        executable: /bin/bash
      register: zsh_installed_module_count

    - name: run brew from zsh
      ansible.builtin.shell: "zsh -c 'brew --version'"
      ignore_errors: true
      register: brew_from_zsh

    - name: assert dotfiles basics are configured
      ansible.builtin.assert:
        that:
          - "'zsh' in ansible_user_shell.stdout"
          - "'10' in zsh_installed_module_count.stdout_lines"
          - "brew_from_zsh.failed == false"
