command_timeout = 1000
[character]
success_symbol = "[»](bold green)"
error_symbol = "[✖](bold red)"

[aws]
disabled = true

# [python]
# disabled = true

[directory]
truncation_length = 8
truncate_to_repo = false
truncation_symbol = "../"

