- name: update homebrew
  homebrew: update_homebrew=yes

- name: applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - 1password
    # - amethyst # tiling window manager
    # - bitbar # for showing custom scripts in the menu bar
    - caffeine # for preventing sleep when doing long tasks
    - karabiner-elements # keyboard remapping
    - google-drive
    # - handbrake
    - monitorcontrol # for brightness control support on external monitors
    # - noti # for notifications
    - obsidian # awesome note taking app
    - rectangle # for window management
    # - signal
    - spotify
    - raycast # spotlight replacement
    - tor-browser
    - uninstallpkg
    - vlc
    - zappy # better screenshot tool
    - zen # privacy and productivity focussed web browser

- name: other helpful command line tools
  homebrew: name={{ item }} state=present
  with_items:
    - bash  # the version of bash that ships with macos (3.2.x) is outdated
    - dockutil # for managing dock items from the command line
    - rsync # the version of rsync that ships with macos (2.6.9) is outdated
    - switchaudio-osx # for switching audio devices from the command line

- name: developer applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - ghostty # terminal app optimized for mac silicon
    - kitty
    - orbstack # docker replacement optimized for mac silicon
    - postico # postgres client
    - visual-studio-code
    # - warp

- name: ensure we have a directory for custom key bindings
  file: path={{ ansible_env.HOME }}/Library/KeyBindings state=directory mode=700

# copy custom macos keybindings
# symlinking causes issues in some apps
# see https://itectec.com/askdifferent/textedit-key-bindings-modified-in-defaultkeybinding-dict-stopped-working/
- name: copying DefaultKeyBinding for custom key bindings in osx text inputs
  copy:
    src: KeyBindings/DefaultKeyBinding.dict
    dest: "{{ ansible_env.HOME }}/Library/KeyBindings"
    mode: 0644

# NOTE: A lot of these seem to be broken/unmaintained
# see https://github.com/sindresorhus/quick-look-plugins
# - name: quicklook plugins
#   homebrew_cask: name={{ item }} state=present
#   with_items:
#     - betterzip
#    - qlmarkdown
#     - qlcolorcode # https://github.com/anthonygelibert/QLColorCode/issues/88#issuecomment-927783435
#     - qlstephen # https://github.com/whomwah/qlstephen/issues/133
#     - quicklook-json # TODO: Verify this works on M1/Apple Silicon

- name: install third party fonts used in terminal and other places
  homebrew_cask: name={{ item }} state=present
  with_items:
    - font-fira-code
    - font-hack
    - font-jetbrains-mono

- name: remove all dock items for a fresh start
  ansible.builtin.shell: dockutil --remove all --no-restart

- name: add desired dock items
  ansible.builtin.shell: dockutil --add '{{ item }}' --no-restart
  with_items:
      - /Applications/Calendar.app
      - /Applications/Brave Browser.app
      - Finder
      - /Applications/Ghostty.app
      - /Applications/Spotify.app
      - /Applications/Visual Studio Code.app
      - /Applications/Zen.app

- name: restart dock to apply changes
  ansible.builtin.shell: killall Dock
