name: release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --deploy
    - name: Converge using Molecule
      run: pipenv run molecule converge
    - name: Login to github container registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PUBLISH_PAT }}
    - name: Get the release version tag
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Commit & publish docker image of release
      run: |
        docker commit molecule_instance docker.pkg.github.com/$GITHUB_REPOSITORY/dotfiles-minimal:${{ steps.get_version.outputs.VERSION }}
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/dotfiles-minimal:${{ steps.get_version.outputs.VERSION }}
